#https://travis-ci.com/
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t alfred/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true alfred/docker-react npm run test

deploy:
  provider: elasticbeantalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "nodeJSApp"
  env: "Nodejsapp-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-120465401207"
  bucket_path: "docker"
  on:
    branch: master

